<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>GSTR_Match</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net45</TargetFramework>
    <Prefer32Bit>True</Prefer32Bit>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Microsoft.VisualBasic">
      <HintPath>../../../../../usr/local/share/dotnet/shared/Microsoft.NETCore.App/10.0.2/Microsoft.VisualBasic.dll</HintPath>
    </Reference>
    <Reference Include="System.Data">
      <HintPath>../../../../../usr/local/share/dotnet/shared/Microsoft.NETCore.App/10.0.2/System.Data.dll</HintPath>
    </Reference>
    <Reference Include="Aspose.Cells">
      <HintPath>../../../Downloads/Bahi-Khata Mahadev Rice/Aspose.Cells.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>../../../Downloads/Bahi-Khata Mahadev Rice/Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="AWSSDK.Core" />
    <Reference Include="System.Core">
      <HintPath>../../../../../usr/local/share/dotnet/shared/Microsoft.NETCore.App/10.0.2/System.Core.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>